/**
 * ktor-sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package webapi

import io.ktor.server.locations.*
import kotlinx.serialization.Serializable
import webapi.models.User

@Serializable
object Paths {
    /**
     *
     */
    @Serializable
    @Location("/users")
    class usersGet

    /**
     *
     * @param id
     */
    @Serializable
    @Location("/users/{id}")
    class usersIdGet(val id: kotlin.Int)

    /**
     *
     * @param id
     * @param user  (optional)
     */
    @Serializable
    @Location("/users/{id}")
    data class usersIdPost(val id: kotlin.Int, val user: User? = null)

}
