/**
* ktor-sample
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package webapi.models


/**
 * 
 * @param id 
 * @param name 
 * @param email 
 */
@kotlinx.serialization.Serializable
data class User(
    val id: kotlin.Int,
    val name: kotlin.String,
    val email: kotlin.String? = null
) 

